docs/basics.rst: Update validate_password() to take 3 arguments
This change updates the sample validate_password() function since it
actually receives 3 arguments when called, i.e. realm, username and
password.

Without this change, the following exception is raised:

    TypeError: validate_password() takes exactly 2 arguments (3 given)